version: "3"
services:
  react-app:
    container_name: mern-colormsgs-react
    image: react-app
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-color-msgs-app
    volumes:
      - ./client/:/usr/src/app
      # - /usr/src/app/node_modules
      
  api-server:
    container_name: mern-colormsgs-express
    image: api-server
    env_file: ./server/.env
    ports:
      - "5000:5000"
    networks:
      - mern-color-msgs-app
    volumes:
      - ./server/:/usr/src/app
      # - /usr/src/app/node_modules
    depends_on:
      - mongo
      
  mongo:
    container_name: mern-colormsgs-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-color-msgs-app
    volumes:
      - mongo-data:/data/db
      
networks:
  mern-color-msgs-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local